# Generated by Django 6.0.7 on 2026-07-12 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PERSON', 'Person'), ('LOCAL_COMPANY', 'Local Company'), ('FOREIGN_COMPANY', 'Foreign Company')], max_length=20)),
                ('full_name', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=100)),
                ('national_id', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NameReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('TEMP', 'Temporary'), ('CONFIRMED', 'Confirmed'), ('EXPIRED', 'Expired')], default='TEMP', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.investor')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicetype')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(default='DRAFT', max_length=50)),
                ('wilaya', models.CharField(max_length=100)),
                ('moughataa', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.investor')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicetype')),
            ],
        ),
    ]
