# Generated by Django 6.0.7 on 2026-07-12 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_servicetype_provisional_validity_days_and_more'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='namereservation',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_reservation', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='namereservation',
            name='status',
            field=models.CharField(choices=[('RESERVED', 'محجوز مؤقتاً'), ('CONFIRMED', 'مؤكَّد (طلب مُرسَل)'), ('REGISTERED', 'مسجَّل نهائياً (ترخيص صادر)'), ('EXPIRED', 'منتهي الصلاحية')], default='RESERVED', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.investor'),
        ),
        migrations.AlterField(
            model_name='project',
            name='moughataa',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='wilaya',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name', 'service_type')},
        ),
    ]
