# Generated by Django 6.0.7 on 2026-07-12 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='provisional_validity_days',
            field=models.PositiveIntegerField(default=180, help_text='مدة صلاحية الترخيص الأولي بالأيام (افتراضياً 6 أشهر)'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='required_inspections_count',
            field=models.PositiveSmallIntegerField(default=1, help_text='عدد التفتيشات الناجحة المطلوبة قبل إصدار الترخيص النهائي لهذا النشاط'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='core.servicetype'),
        ),
    ]
