# Generated by Django 6.0.7 on 2026-07-13 20:50

import core.storage
import operations.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "operations",
            "0002_inspection_checklist_completed_inspection_latitude_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="receipt",
            field=models.FileField(
                storage=core.storage.SupabaseStorage(bucket_name="payment"),
                upload_to=operations.models.payment_upload_path,
            ),
        ),
    ]
