# Generated by Django 6.0.7 on 2026-07-12 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_servicetype_provisional_validity_days_and_more'),
        ('projects', '0002_namereservation_project_alter_namereservation_status_and_more'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='completed_inspections_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'مسودة'), ('SUBMITTED', 'تم الإرسال'), ('UNDER_REVIEW', 'قيد المراجعة الإدارية'), ('NEEDS_CORRECTION', 'بحاجة لتصحيح'), ('INSPECTION_SCHEDULED', 'بانتظار المعاينة'), ('INSPECTION_DONE', 'تمت المعاينة'), ('PAYMENT_PENDING', 'بانتظار رفع المخالصة'), ('PAYMENT_VERIFIED', 'تم تأكيد المخالصة'), ('PROVISIONAL_LICENSE', 'ترخيص أولي/مؤقت'), ('FOLLOWUP_INSPECTIONS', 'تفتيشات متكررة'), ('FINAL_LICENSE', 'ترخيص نهائي صادر'), ('REJECTED', 'مرفوض نهائياً')], default='DRAFT', max_length=25),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='document',
            name='rejection_reason',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('PENDING', 'قيد المراجعة'), ('APPROVED', 'مقبولة'), ('REJECTED', 'مرفوضة')], default='PENDING', max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('project', 'requirement')},
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=25)),
                ('to_status', models.CharField(max_length=25)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='workflow.application')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
