# Generated by Django 6.0.7 on 2026-07-13 20:50

import core.storage
import workflow.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0002_application_completed_inspections_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                storage=core.storage.SupabaseStorage(bucket_name="documents"),
                upload_to=workflow.models.document_upload_path,
            ),
        ),
    ]
